# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0fc9c4549845db3b587b7a5db42372f030bd8155e3efad0c3b9c0d5cdda9c044ed902265f54db1ebe225c6fca0a8040aca56e67c66830b1001abdf16f705453

test:
  secret_key_base: f35346907ea41e30d21b5eea933925dfc181f855d80b593f1bec8f6aa2846a4246b3dc3c2b473ab893be729706febf5e096c769fff1901dcf487c95b2f71d413

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
